version: "3"
services:
  bd:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rwe_clients

    ports:
      - "5445:5432"

  api:
    build:
      context: ./back
    depends_on:
      - bd
    environment:
      DB_HOST: bd
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rwe_clients
      SECRET_KEY: "ff67b5c47a98707a51ebd307dc88de7c"

    ports:
      - "3000:3000"

  # front:
  #   build:
  #     context: ./front
  #   depends_on:
  #     - api
  #   ports:
  #     - 5173:5173
  #   environment:
  #      REACT_APP_API_URL: http://api:3000/