# Use a imagem Node.js
FROM node:14

# Diretório de trabalho dentro do contêiner
WORKDIR /app/react-app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da API para o contêiner
COPY . .

# Exponha a porta em que o Vite irá ouvir (normalmente é 3000)
EXPOSE 5173

# Comando para iniciar o servidor de desenvolvimento do Vite
CMD ["npm", "run", "dev"]