# Use a imagem base Node.js para construir o aplicativo React
FROM node:14 as build

# Diretório de trabalho dentro do contêiner
WORKDIR /app/react-app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./
COPY ./package-lock.json .

# Instale as dependências
RUN npm install

# Copie o restante do código do aplicativo React para o contêiner
COPY . .

# Construa o aplicativo React
RUN npm run build

# Use uma imagem mais leve do servidor da web para servir o aplicativo React
FROM nginx:alpine

# Copie os arquivos construídos do aplicativo React para o diretório do servidor da web
COPY --from=build /app/react-app/build /usr/share/nginx/html

# A imagem do Nginx já expõe a porta 80, portanto não é necessário usar o comando EXPOSE

